In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

<class 'numpy.ndarray'>
1
2
3
4
5


In [7]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b[0, 0],b[0, 1],b[0, 2])
print(b[1, 0],b[1, 1],b[1, 2])

1 2 3
4 5 6


In [8]:
b = np.array([1, 2, 3], int)
print(b)
b = np.array([1, 2, 3], float)
print(b)

[1 2 3]
[1. 2. 3.]


In [12]:
a = np.arange(5)
print(a)
a = np.arange(1, 6, 2)
print(a)

[0 1 2 3 4]
[1 3 5]


In [23]:
c = np.zeros(2)
print(c)
c = np.zeros((2, 2))
print(c)

e = np.ones(2)
print(e)
e = np.ones((2, 2))
print(e)

e = np.full(2, 7)
print(e)
e = np.full((2, 2), 7)
print(e)

[0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1.]
[[1. 1.]
 [1. 1.]]
[7 7]
[[7 7]
 [7 7]]


In [25]:
i = np.array([[1, 2, 3],[3, 4, 5]])
i = np.zeros_like(i)
print(i)

i = np.array([[1, 2, 3],[3, 4, 5]])
i = np.ones_like(i)
print(i)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [38]:
l = np.eye(3)
print(l)

l = np.eye(3, k=1) # 往上移1格
print(l)

l = np.eye(3, k=2) # 往上移2格 
print(l)

l = np.eye(3, k=-1)# 往下移1格 
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [40]:
a = np.arange(16)
print(a)
a = a.reshape((4, 4))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# 陣列屬性

|屬性|說明|
|--------|:--------------:|
|dtype   |int32, int64, float32, float64|
|size    |# of array|
|shape   |mxn|
|itemsize|每個元素使用byte總數|
|ndim    |1D, 2D, 3D|
|nbytes  |每個陣列使用byte總數|

# 走訪

In [42]:
a = np.arange(5)
print(a)
for c in a:
    print(c, end=' ')

[0 1 2 3 4]
0 1 2 3 4 

In [47]:
a = np.arange(4)
print(a)
a = a.reshape((2,2))
for c in a:
    print(c, end=' ')
print()
for c in a:
    for b in c:
        print(b, end=' ')

[0 1 2 3]
[0 1] [2 3] 
0 1 2 3 

# 亂數

|屬性|說明|
|---------|:--------------:|
|seed(int)|

In [50]:
x = np.random.seed(int)

TypeError: Cannot cast array from dtype('O') to dtype('int64') according to the rule 'safe'

In [53]:
a = np.random.rand(5)
print(a)
a = np.random.rand(3,2)
print(a)

[0.86259419 0.29898363 0.08960979 0.17473386 0.19504893]
[[0.79023965 0.84132962]
 [0.38014324 0.95400835]
 [0.87999368 0.19133509]]


In [64]:
c=np.random.randint(5, 10, size=5)
print(c)
c=np.random.randint(5, 10, size=(2, 3))
print(c)

[9 7 9 7 6]
[[9 6 6]
 [5 6 9]]


# 四則運算

In [76]:
a = np.arange(3)
b = np.arange(3, 6, 1)
print(a)
s = 5
print(a + s)
print(a * s)
print(a / s)
print(str(a) + " dot " + str(b) + " =", a.dot(b))

[0 1 2]
[5 6 7]
[ 0  5 10]
[0.  0.2 0.4]
[0 1 2] dot [3 4 5] = 14


In [89]:
a = np.arange(1,9+1)
print(a)
b, c, d = a[1:3], a[:4], a[3:]
print(b)
print(c)
print(d)
# array[start:end:step]
b, c, d = a[2:9:3], a[::2], a[::-1]
print(b, c, d)
print(sum(a))


[1 2 3 4 5 6 7 8 9]
[2 3]
[1 2 3 4]
[4 5 6 7 8 9]
[3 6 9] [1 3 5 7 9] [9 8 7 6 5 4 3 2 1]
45


In [103]:
a = np.arange(11, 36)
a = a.reshape(5, 5)
print(a)
b = a[0, 1:4]
print(b)
b = a[1:4, 0]
print(b)
b = a[:2, 1:3]
print(b)
b = a[:, 1]
print(b)
b = a[::2, ::2]
print(b)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[12 13 14]
[16 21 26]
[[12 13]
 [17 18]]
[12 17 22 27 32]
[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [109]:
a = np.arange(1,9+1)
print(a)
b = a[[1, 3, 5, 7]]
print(b)
b = a[range(6)]
print(b)
a[[2, 6]] = 10
print(a)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[1 2 3 4 5 6]
[ 1  2 10  4  5  6 10  8  9]


In [119]:
a = np.arange(1, 10)
a = a.reshape(3, 3)
print(a)
c = a[[0, 1, 2], [0, 1, 0]]
print(c)
c = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 7]
[1 5 7]


In [126]:
b = np.arange(1, 6)
print(b)
mask = (b%2 == 0)
print(mask)
a = b[mask]
print(a)
b[b % 2 == 0] = -1
print(b)

[1 2 3 4 5]
[False  True False  True False]
[2 4]
[ 1 -1  3 -1  5]


In [154]:
b = np.arange(1, 7).reshape(3, 2)
print(b)
mask = (b > 2)
print(mask)
a = b[mask]
print(a)
b[b > 2] = -1
print(print(b))  

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[[ 1  2]
 [-1 -1]
 [-1 -1]]
None


In [157]:
a = np.arange(1, 7).reshape(2, 3)
print(a)
b = a.ravel()
print(b)
b = np.ravel(a)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [160]:
b = np.arange(1, 7).reshape(2, 3)
print(b)
print(b.T)
print(b.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [163]:
a = np.array([1, 2, 3])
print(a) 
b = a[:, np.newaxis]
print(b)
print(b.shape)
b = a[np.newaxis, :]
print(b)
print(b.shape)

[1 2 3]
[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)


In [193]:
a = np.array([1, 2, 3])
b = a.copy() # 如果寫 b = a 會造成 a b 連動
b.fill(4)
print(b)
print(c)

c = np.concatenate((a, b))
print(c)
a.resize(2, 2)
a.fill(1)
print(a)
b.resize(2, 2)
b.fill(2)
print(b)
c = np.concatenate((a, b), axis=0)
print(c)
c = np.concatenate((a, b), axis=1)
print(c)

[4 4 4]
[[1 1 2 2]
 [1 1 2 2]]
[1 2 3 4 4 4]
[[1 1]
 [1 1]]
[[2 2]
 [2 2]]
[[1 1]
 [1 1]
 [2 2]
 [2 2]]
[[1 1 2 2]
 [1 1 2 2]]


In [223]:
# brocast
a = np.arange(1, 10).reshape(3, 3)
print(a)
print("a's shape" + str(a.shape))
b = np.array([0, 1, 0])
print(b)
print("b's shape" + str(b.shape))
c = a + b 
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
a's shape(3, 3)
[0 1 0]
b's shape(3,)
[[1 3 3]
 [4 6 6]
 [7 9 9]]
